### ISSUE TITLE
Spotify connect

### ISSUE THREAD

**Issue by SeyedGH** [marcelveldt/plugin.audio.spotify#73]
When I turn on spotify connect, I get "Please connect to this device with the Spotify app on your phone to login or enter your credentials in the settings dialog." 
And when i choose on my phone listen from this device i get the same message.
Am I doing something wrong?

**Comment by marcelveldt** [comment]
what platform ?
kodi log ?

**Comment by Too5shot** [comment]
Im having the same problem, using an android phone and kodi krypon on windows 10

**Comment by marcelveldt** [comment]
can you please provide your kodi logfile ?
can you see the kodi player on your phone ?

**Comment by Too5shot** [comment]
[kodi.log](https://github.com/marcelveldt/plugin.audio.spotify/files/1865962/kodi.log)
Yes i can see the kodi player from my phone

**Comment by marcelveldt** [comment]
thanks for the log but there is nothing in there I can use... 
Please enable Kodi debug logging first, then fresh start Kodi (with debug logging enabled) and try to connect your phone to the Kodi player or enter username+password in the settings for the addon.

Thanks!

**Comment by Too5shot** [comment]
[kodi.log](https://github.com/marcelveldt/plugin.audio.spotify/files/1865970/kodi.log)
Here you go. and i tried both connecting my phone and entering my username and password but still got the same message

**Comment by marcelveldt** [comment]
nothing wrong in the logs... did you try to wait a bit longer ?
might be that it just takes a minute before it finishes the initial authentication

**Comment by marcelveldt** [comment]
and did you also try a reboot ?

**Comment by Too5shot** [comment]
Yes , application restart and full system reboot

**Comment by marcelveldt** [comment]
new version is up on the repo, please give that a try, hopefully fixed. If not, there will be a bit more info in the (debug) log for me to work with.

**Comment by Too5shot** [comment]
Thanks, will check it out as soon as i get home.

**Comment by Too5shot** [comment]
I have tried to update but im not even sure it updated anything because it is still the same version (1.1.50).
and im still getting getting the same message

**Comment by marcelveldt** [comment]
version should be 1.1.51....

**Comment by Too5shot** [comment]
I only find 1.1.50 in the repo... Am i missing somthing obvious here?

**Comment by marcelveldt** [comment]
my fault... forgot to update, will do within an hour or so

**Comment by Too5shot** [comment]
Ok, thanks

**Comment by felipebrauna** [comment]
Same issue here, waiting for the 1.1.51 fix...

**Comment by marcelveldt** [comment]
1.1.52 is on the repo now, that should fix the issues

**Comment by saba1970** [comment]
I have installeer 1.1.52 and I still have the this issue. Do I something wrong?

**Comment by marcelveldt** [comment]
@saba1970 did you actually try to connect to the Kodi player with your phone to authenticate it ? You can also enter the credentials in the addon's settings. 

If it keeps failing you, please enable Kodi debug logging and collect your logfile for me to investigate.

**Comment by saba1970** [comment]
Hallo Marcel, I have entered the credentials in the addon's settings. Friday night Spotify on the Kodi did work fine. I have this issue on both nu RPI's. I use LibreElec.

**Comment by marcelveldt** [comment]
some changes were needed to fix some other issues. Other than that it should still work fine or even better but there can always be something I overlooked. Please provide me the your kodi log, otherwise I can't help you

**Comment by saba1970** [comment]
Hallo Marcel, here the logging. 
Http://ix.io/15IE

**Comment by saba1970** [comment]
Logging: Http://ix.io/15IO

**Comment by Too5shot** [comment]
I have tested 1.1.52 now and it is working for me, just updated and restartet kodi

**Comment by marcelveldt** [comment]
@Too5shot ok great, thanks for reporting back

@saba1970 sorry, those links don't seem to be working. You do know that you can send the file here directly on github ?

**Comment by saba1970** [comment]
How can I upload the logging?

**Comment by saba1970** [comment]
[kodi.log](https://github.com/marcelveldt/plugin.audio.spotify/files/1866413/kodi.log)

Hallo Marcel, can you use this logging?

**Comment by jnk22** [comment]
I have had the same problem, and also when using the Spotify addon just in Kodi itself (same error message).

Both seems to be fixed with version 1.1.52 for me :)

Thanks a lot @marcelveldt !

**Comment by ray2301** [comment]
The fix didn't work for me on leia x64 windows
I'm going back to 1.1.34...again...that one is the only one that always worked for me without a problem but without the possibility to connect to spotify connect. i don't know why, every version I try it clean or update - it's always the same thing. And now I can't even login whether it's a clean or updated setup (even with 1.1.52).

**Comment by ray2301** [comment]
I mean it works if I close spotty.exe while on 1.1.50 and then update to 1.1.52. Spotty.exe opens up again and everything works untill I close kodi and close spotty.exe again. Then I open kodi and I'm on 1.1.52 but Please connect to this device...

**Comment by marcelveldt** [comment]
I think that the spotify connect player is failing on Windows. For now Windows users should disable it until I figure out why

**Comment by ray2301** [comment]
Thank you, Marcel. Works and plays great without it.

**Comment by GAZ082** [comment]
I'm using OpeneElec and the repo still shows 1.1.50. Dont forget linux users!  :)

**Comment by GAZ082** [comment]
Never mind, downloaded and update manualy.

How does the Spotify Connect work? Kodi is decting my phone or my browser as "playback devices" but nothing is coming out.

**Comment by marcelveldt** [comment]
new version on the repo (1.1.53) which should fix the issue with the connect player.

@GAZ082 sometimes it can take a while before changes on the repo are visible because of caching, just wait a bit longer or reboot to speed it up.

Spotify connect is implemented this way:

- You can use the Spotify app on your phone to authenticate, so you don't need to store credentials in the addon/kodi. Just select your kodi device once as playback target and the token will be exchanged.

- You can use your kodi device as playback target, so you can use your phone to browse and kodi to play.

- You can use kodi to browse but another device to play (this is the default on android devices)

**Comment by ray2301** [comment]
1.1.53 finally works for me with spotify connect, you rule :)

**Comment by saba1970** [comment]
Hello Marcel, but I'm still having the issue with 1.1.53. What do I wrong?
[kodi.log](https://github.com/marcelveldt/plugin.audio.spotify/files/1868036/kodi.log)

**Comment by marcelveldt** [comment]
@saba1970 your log is full of errors from all kind of banned addons and other mess. It's completely unreadable because of all the errors. I suggest you to grab a new SD card with fresh install of LibreELEC and the spotify addon to see if that works. If that works, your issue is related to your current setup

**Comment by saba1970** [comment]
Hello Marcel, I have this issue only on the RPI's. I have just tested Kodi on Win10 and there everything works fine.

**Comment by marcelveldt** [comment]
OK, I will test later today with a pi. If you could also test with a fresh setup that would be great.

**Comment by JayOne73** [comment]
Also problems with login on RPI  (Kodi 17.4) since this weekend. 

In the kodi.log the next lines keeps on appearing:

10:17:49.555 T:1711981488   DEBUG: plugin.audio.spotify --> retrieving token...
10:17:49.667 T:1711981488   DEBUG: plugin.audio.spotify --> request_token_spotty stdout:
10:17:49.763 T:1711981488   DEBUG: Previous line repeats 1 times.
10:17:49.764 T:1711981488   DEBUG: plugin.audio.spotify --> Couldn't request authentication token. Username/password error ? If you're using a facebook account with Spotify, make sure to generate a device account/password in the Spotify accountdetails.

When checking the settings.xml the right user/password settings are filled.

[kodi.log](https://github.com/marcelveldt/plugin.audio.spotify/files/1868173/kodi.log)

**Comment by TrespaMMG** [comment]
Same problem since friday, before it worked perfectly kodi 17.4 with spotify , now it got updated to spotify app 1.1.53 and login fails. Dont know which version I had what worked before the update, since there are several new updates

**Comment by saba1970** [comment]
Hallo Marcel, I have tested it with a fresh setup. There is no message, but I have no sound and he can't find the songs in the playlist.

**Comment by gismo2004** [comment]
When using my device-id im able to connect without problems, but im facing a problem when playing music from playlist. it is not automatically continuing. and also "skipping" a track ends up in a "stop". i need to press play again, to listen further. Not sure if this should be reported somewhere else, but since it is a issue with "connect" i decided to post it here...

BTW: how would be the "workflow" without credentials? i mean, how to connect my phone-app to kodi? (running on intel nuc with ubuntu, kodi standalone)

https://gist.github.com/gismo2004/addbf5d5530a3b8cc357f8407893b1e0

**Comment by JayOne73** [comment]
Some various restarts and updating to 1.1.53, I can now login into spotify again. Browsing through my library and playlists seem to work, only I have no sound when playing a track. 

Both Spotify connect options are disabled.

**Comment by GAZ082** [comment]
Hi there. Updated to .53. KODI detects my browser and mobile. When i'm playing with my phone or browser and i activate it in Kodi, the playback in either device (phone or browser) stops but from my Kodi i still get nothing.

I logged the whole stuff, hope this can help you out.

Dude, if you get this working I'll donate 10 usd.

Log: http://termbin.com/azh9

Thanks!

**Comment by felipebrauna** [comment]
Still don't working on my pi with the 1.1.5.3 version. I'll provide the log soon...

**Comment by marcelveldt** [comment]
version 1.1.55 will be on the repo within a few minutes. Please test if that fixes the issue.
For now I've disabled the auto discovery stuff (use your phone to authenticate) on LibreElec because the mdns implementation of librespot was conflicting with avahi on libreelec. 

So, on LibreElec, you must use username and password to authenticate.

**Comment by GAZ082** [comment]
1. Updated to 1.1.55
2. Rebooted.
3. Still nothing.
4. In settings unchecked the Enable this device as Spotify target. Rebooted, enabled again, rebooted.
5. Nothing. My Kodi is not shown in my phone as a device but from KODI do see my phone or browser and when i select them the reproduction in either device stops but goes nowhere.

Is this perhaps a port issue? What port Spotify uses?

**Comment by GAZ082** [comment]
Yes, yet there is no Kodi in my Spotify Devices list. Let's see if others have this issue with OpenElec. It's late here, i'll follow up during the week. Thanks.

**Comment by marcelveldt** [comment]
Hmmm, I have tested with MacOS, Windows and LibreElec x86. Only thing I did not test is raspberry pi.  Maybe the issue is only with pi.

**Comment by GAZ082** [comment]
I'm using it with a Cubox-i4 which is ArmV9. I'll get you the logs if i'm not too tired when i get home today, pehaps the issue is with ARM processors, either way we should get something in the logs, right?

**Comment by saba1970** [comment]
Hello Marcel, I have tested 1.1.55 on a Pi with LibreElec. Now I have the following strange issue. When I enter the credentials in the addon settings, they immediately disappear. I have disabled the option "Enable this device as Spotify target".

**Comment by GAZ082** [comment]
@saba1970 but can you play music? I actually never entered using the KODI interface, i put them manualy in the settings.xml file of the plugin.

**Comment by saba1970** [comment]
@GAZ082 No, I can't even start Spotify addon.

**Comment by saba1970** [comment]
@GAZ082: where can I find the settings.xml on a Pi?

**Comment by marcelveldt** [comment]
@saba1970 can you send me a Kodi debug log after this strange thing with the credentials happened ?

**Comment by marcelveldt** [comment]
@GAZ082 something to try instead of enabling Kodi debug log is to force debug logging in the addon itself. For that you need to open the file called utils.py (in resources/lib of the addon). Somewhere on the top lines there should be a DEBUG=False statement which you need to change to True and reboot Kodi. Maybe that will result in some more verbose logging of what is going on.

**Comment by GAZ082** [comment]
@saba1970 /.kodi/addons/plugin.audio.spotify/resources (notice the .kodi is a hidden folder).

Then in settings.xml, find this line near the top:
```
 <setting id="username" type="text" label="11001" default="**USER HERE**" visible="eq(2,false)"/>
        <setting id="password" type="text" option="hidden" label="11002" default="**PASS HERE**" visible="eq(1,false)"/>

```

@marcelveldt will do and report back!

**Comment by saba1970** [comment]
@marcelveldt: here the kodi.log
[kodi (2).log](https://github.com/marcelveldt/plugin.audio.spotify/files/1872780/kodi.2.log)

I have also tested with a fresh installation of LibreElec. Same issue.

**Comment by marcelveldt** [comment]
@saba1970 sorry, that log is kind of useless as it only contains a small part of the startup sequence which is also spammed by some banned addons. If you could deliver me the (full!) logfile of the fresh installation that would be great, otherwise you'll have to wait a bit untill I have some time to setup a pi with libreelec to test with later this week.

**Comment by saba1970** [comment]
@marcelveldt: Reset LiberElec. Install Spotify addon on the Pi. Reboot Pi. Start Spotify. Set credentials. Reboot Pi. Start Spotify. Spotify shows me menu. I select MyMusic -> MyPlaylist. Spotify search very long, but find nothing. The same when I open a playlist in Spotify or when I search by example U2. I got a menu with artist, playlist, albums and songs. I click on artist. Spotify search very long, no results.
[kodi (2).log](https://github.com/marcelveldt/plugin.audio.spotify/files/1873058/kodi.2.log)

**Comment by JayOne73** [comment]
Same problems as saba1970 above on RPI setup with Kodi 17.4 (and plugin version1.1.55).

From line 1244 in the logfile there are some warnings:
[kodi.log](https://github.com/marcelveldt/plugin.audio.spotify/files/1873087/kodi.log)

**Comment by GAZ082** [comment]
OKEY BOY. Here is the new log with the forced debug:
http://termbin.com/niti

Again, from my mobile i do NOT see Kodi. However, from Kodi, I do see my mobile as Active while it's playing something, when i select it, the play in my mobile stops.

**Comment by saba1970** [comment]
@marcelveldt. It is really 1.1.55. I will send you this evening a printscreen of the version.

**Comment by saba1970** [comment]
@marcelveldt: here an update and see also the attachments.
![imag0066](https://user-images.githubusercontent.com/37978141/38326654-9ccc6a96-3846-11e8-95a7-d2ed10046620.jpg)
[repository.marcelveldt-1.0.1.zip](https://github.com/marcelveldt/plugin.audio.spotify/files/1877062/repository.marcelveldt-1.0.1.zip)
Fresh installation from LibreElec. Installation of Spotify with attached zip-file. I'm very happy. I had a connection with Spotify and I had sound. So far so good. Then I installed another Pi. Fresh installation LibreElec. New installation of Spotify with attached zipfile. Connection with Spotify, but no sound.
I installed the first Pi again. Cnnection with Spotify, but there was no sound. How is that possible?

**Comment by saba1970** [comment]
@marcelveldt: I have restored a backup with repo 1.1.44. Spotify works than fine on the Pi's.

**Comment by GAZ082** [comment]
@saba1970 does spotify connect work?

@marcelveldt i installed 1.1.44 and now my mobile detects Kodi but when i select it to play, it stays "trying to connect" for a few seconds then desists. The log has some stuff: http://termbin.com/b2ja

**Comment by felipebrauna** [comment]
So guys, after i do some tests in my Libreelec Kodi 18 (Leia) Beta on Pi and everything (Spotify  connect and local player) Works like a charm since the first attempt, now It seems this issue, at least on the Pi is related to something in the version Krypton 17.4.

**Comment by marcelveldt** [comment]
@GAZ082 1.1.44 will not work with Connect, it's the whole reason I needed to change stuff. You must use the latest version to have Connect support.

**Comment by marcelveldt** [comment]
@felipebrauna It is possible that there was a specific issue with Kodi 17.4 . I have seen issues too on my test libreelec setup when using version 17.4. I suggest to use 17.6 (the latest version)

**Comment by GAZ082** [comment]
@marcelveldt I'm using Kodi 17.3, will see if can update to 17.6 tonight and test again. Never realized there was a newer Kodi version as i just installed OpenElec for the first time a week ago. Fingers crossed!

**Comment by GAZ082** [comment]
Okey, installed LibreElec which comes with Kodi 17.6 and now it detects and "plays" but nothing comes out of the speakers. Here is the log: http://termbin.com/235t

I found LibreElec has a similar plugin called Librespot which works as a Spotify Connect devices with no issues.

**Comment by saba1970** [comment]
@marcelveldt: I have tested 1.1.55 with Kodi 17.6 with LibreElec. I got the same message  "Please connect to this device with the Spotify app on your phone to login or enter your credentials in the settings dialog." I use now 1.1.44 because I don't need Spotify connect. So for me the "old" Spotify works fine.

**Comment by JayOne73** [comment]
Also returned to 1.1.44 because I don't really need the connect option (already using raspotify for that) and upgrading to Kodi 17.6 seems a no go on a RetroPie setup.

**Comment by marcelveldt** [comment]
I will take another look this weekend. For now you can indeed use version 1.1.44 if you don't need connect

**Comment by Matheos96** [comment]
I am having this issue too. Latest version OSMC and latest spotify plugin. Everytime I launch OSMC/Kodi it pops up telling me to login using phone (which I don't understand how works) or in the settings app which I am already logged into... Everything works tho but annoying to get the message everytime even though I am, as I said, already logged in.

**Comment by gpchampion** [comment]
Can someone tell me where I get 1.1.44 from? I've found 1.1.46 and that seems solid on OSMC. Been playing playlists of 70+ tracks all day here. No drop outs as far as I can make out/hear!

**Comment by gpchampion** [comment]
BTW, I will restart OSMC later and see if I get the creds prompt on 1.1.46.

**Comment by JayOne73** [comment]
@gpchampion you can get the different versions via **[this link]**(https://github.com/marcelveldt/repository.marcelveldt/tree/master/plugin.audio.spotify)

**Comment by gpchampion** [comment]
Thanks for that, I looked, didn't find in there, failed!!!

**Comment by Matheos96** [comment]
Any solutions yet? I still have this "please connect" message even though I am already connected + now with a new update I also get "will open in default browser..." which is literally not possible on RPi since OpenElec, OSMC or LibreElec don't have any browser...

Issue about this here: https://github.com/marcelveldt/plugin.audio.spotify/issues/86

**Comment by maxgrass** [comment]
@Matheos96 

- Try removing the app from kodi, 
- then removing the connected app from Spotify settings https://www.spotify.com/de/account/apps/ 
- and then installing the addon again.
- Now put your credentials (for me only the **login name and NOT email** worked + password).
Note: kodi nightlies are very unstable so maybe it's that as well.

**Comment by austin-agronick** [comment]
@maxgrass I tried your solution and it seems the issue for me is that Kodi fails to launch my web browser to connect to my Spotify account. However at first launch the addon does crash Kodi, but no web browser opens.

**Comment by Matheos96** [comment]
@maxgrass I tried but it did not remove my credentials when I uninstalled the app, so when I installed it again I did never have to enter my credentials again, I was already logged in. Also the first thing I saw was that box when I launched the app again after new install.

There has to be some cache/save files stored that saves the login info even if I remove the app... Anyone know where?

The app automatically got added to connected apps instantly after me launching it again after reinstall too

**Comment by yuusou** [comment]
@marcelveldt I too, on the RPi 1 B with the latest stable OSMC, am having issues with Spotify Connect. When I first open the add-on, I get asked to log in with my phone and that works flawlessly. After that my phone can no longer see the add-on but the add-on can see my phone. I can even play music on my phone controlled from the add-on but not vice versa.

**Comment by lutel** [comment]
@yuusou I have the same problem, Kodi 17.5 on QNAP, Spotify on my phone doesn't recognize Kodi plugin anymore. I could play couple of songs with spotify connect, but after a while the "Kodi@QNAP" device disappeared from list.

**Comment by 466** [comment]
Just fyi, i can confirm spotify 1.1.56 not working properly on RP3

I am on Milhouse builds, Kodi-18-LibreELEC-9

1.1.56:
login impossible: "No credentials have been set or the login failed"
and back to 1.1.44:
local playback works, spotify connect does not (as marcelveldt already stated)

**Comment by triceo** [comment]
On 1.1.58, with latest LibreELEC:

- Login does not work, says "No credentials have been set or login failed"
- When trying to set credentials, whatever I type into the username/password fields quickly disappears before I can save the dialog.

**Comment by pstroinski** [comment]
On 1.1.58 and Kodi 17.6, Ubuntu installation - same problem.
 "Please connect to this device with the Spotify app on your phone to login or enter your credentials in the settings dialog."

Downgrade to 1.1.44 makes it work again

**Comment by prateek33** [comment]
I just started having this problem after weeks of using this fine. I can't even see kodi on spotify connect on my phone. I am on Kodi Leia and app version 1.1.58. Do we have any workarounds? I verified that the username and password in app's setting is perfectly fine.

**Comment by aulbricht** [comment]
Also trying on Kodi Leia 18.5 and getting the error "please connect to this device with the spotify app on your phone..." After restarting Kodi, I was able to connect from my mobile device Spotify app to Kodi as an audio source. So far so good. The problem is Spotify app and Kodi add-on both think it's playing music, but I only have silence. Any ideas as to why? Note: Kodi audio otherwise works fine (e.g. for movies).

**Comment by Philippe-Brodeur-JCI** [comment]
I have librelec 9.2.6 on a pi 4. I installed Spotify 1.1.58 by marcelveldt.

I created a 'free not premium' user account on spotify and i can log to it using my windows 10 laptop.
But when i try to login to marcelveldt's implementation of Spotify, i get the following error message:

"No credentials have been set or the login failed"
"Please enter you credentials in the addon setting"

Now i know i have entered them (very complex username) and it is working in Win10.
i've tried enabling the log, even the JSON-RPC requests (by any chance) but can't get any clue, nothing logs...

I am a programmer myself, if you give me a couple of hints maybe i can debug my way out.

Thanxs
